#+OPTIONS: toc:nil num:nil author:nil date:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-------
* *Arturas Eidukas*
-----
London, E1 3HR \\
07562898069 \\
iwiivi@gmail.com \\
github: https://github.com/finnkauski/ \\
-----
- Data Scientist
- Software Developer
- Economic Analyst
-----

#+BEGIN_blockquote
/Delivering data-driven business solutions with a pragmatic attitude and a focus
on software./
#+END_blockquote


Pragmatic Data Scientist with a background in Economic Statistics, interest in software
development and a delivery-focused attitude towards business problems. Able to
leverage existing knowledge and experience, learn and adapt quickly and
consistantly deliver high quality outputs in an agile fashion.

I work by the Robert C. Martin's - [[https://blog.cleancoder.com/uncle-bob/2015/11/18/TheProgrammersOath.html][*Programmers Oath*]]

-----
* Education
-----
- BSc Hons. Economics (with industrial placement), 1st class \\
  University of Bradford, 2012 - 2016
-----
* Skills
-----
- Languages:
  - *main:* Python
  - *familiar:* R, SAS, Haskell, Rust
  - *communication:* Russian, English, Lithuanian
- Other Technologies:
  - PySpark, SQL, D3, HTML, CSS, Bash, Git, Unix, RevealJS
- Soft Skills:
  - Business acumen
  - Agile working
  - Adaptability
  - Written and oral communication
  - Leveraging cross-disciplinary teams
-----
* Expertise
-----
#+begin_row

#+begin_col-4
- Natural Language Processing
- Object detection and Image Segmentation pipelines
- Distributed computing
- Developing Web-app front-ends to show Data Science prototypes
- Applying software development practices to Data Science projects
#+end_col-4

#+begin_col-8
- Data and Quantitative analysis
- Reproducible analytical pipelines
- Inflation Statistics
- Presenting data science topics to non-technical audiences
#+end_col-8

#+end_row
-----
* Professional Experience
-----
*Office for National Statistics* ([[https://datasciencecampus.ons.gov.uk/][Data Science Campus]] since May 2018) \\
*Data Scientist* (Dec 2017 to Present) | *Economic Researcher* (Sep 2015 to Dec 2017)
-----
Contributed valuable data analysis and programming expertise to various
projects and publications across the Office for National Statistics, while also
promoting adoption of open-source tools for data analysis through mentoring and
showing its value.
Example projects:
- Image analysis of receipts data to extract purchase information to supplement
  existing survey methods.
- Natural Language Processing to help high-profile Government stakeholders [[https://datasciencecampus.ons.gov.uk/o-p-t-i-m-u-s-turning-free-text-lists-into-hierarchical-datasets/][better utilise their data.]]
- Developed distributed computing pipelines as part of [[https://www.ons.gov.uk/economy/nationalaccounts/balanceofpayments/articles/uktradedevelopmentplan/achievementsandforwardlookoctober2018][Trade Statistics
  transformation]].
- Developed automated Data Processing pipelines to support business as usual
  publications across Price Statistics division.
-----
* Mentoring
-----
- Mentored several [[https://www.gov.uk/government/publications/data-science-accelerator-programme/introduction-to-the-data-science-accelerator][data science accelerator progremme]] students on their data
  science projects (NLP & Satellite image segmentation). Both projects have been
  taken further within their respective institutions and are creating value.
